### PR TITLE
fix ui freezing

### LINKED ISSUE #942: Still UI freezing in RPC mode

### PR DESCRIPTION
**Pull request by ipdae**
### Description

1. resolve #942 
2. use UniTask.Run instead of getStateAsync call.

### How to test

1. First step.

### CODE REVIEW

File: nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs [hunk 1]
```diff
@@ -118,9 +118,9 @@ private static void UpdateGoldBalanceState(GoldBalanceState goldBalanceState)
             States.Instance.SetGoldBalanceState(goldBalanceState);
         }
 
-        private void UpdateAvatarState(AvatarState avatarState, int index)
+        private async void UpdateAvatarState(AvatarState avatarState, int index)
```
Comment (longfin) [inline nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs:121]: We can just return `Task` instead of `async` keyword if there is no statement other than `await`.

```csharp
        private Task UpdateAvatarState(AvatarState avatarState, int index)
            => States.Instance.AddOrReplaceAvatarState(avatarState, index);
```

File: nekoyume/Assets/_Scripts/State/States.cs [hunk 2]
```diff
@@ -86,7 +87,7 @@ public void SetWeeklyArenaState(WeeklyArenaState state)
         /// 최초로 할당하거나 기존과 다른 주소의 에이전트를 할당하면, 모든 아바타 상태를 새롭게 할당된다.
         /// </summary>
         /// <param name="state"></param>
-        public void SetAgentState(AgentState state)
+        public async void SetAgentState(AgentState state)
```
Comment (longfin) [inline nekoyume/Assets/_Scripts/State/States.cs:90]: `async void` returns no exception even if thrown from its body. Unless it is a special case like a callback, it is better to specify that it returns a `Task`.

```suggestion
        public async Task SetAgentState(AgentState state)
```

File: nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs [hunk 3]
```diff
@@ -143,7 +143,7 @@ public void BackToLogin()
             login.Show();
         }
 
-        private void Init(int index)
+        private async void Init(int index)
```
Comment (longfin) [inline nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs:146]:
```suggestion
        private async Task Init(int index)
```

File: nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs [hunk 4]
```diff
@@ -348,7 +348,7 @@ public override void Show(bool ignoreShowAnimation = false)
             StartCoroutine(StartSynopsis(skipPrologue));
         }
 
-        public void End()
+        public async void End()
```
Comment (longfin) [inline nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs:351]:
```suggestion
        public async Task End()
```

**Comment by hskim881028** [comment]
It seems to conflict with https://github.com/planetarium/NineChronicles/pull/947/files 👀

File: nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs (hunk 3 above)
Comment (ipdae) [reply nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs:146]: it can't change Task because `Init` using unityEvent callback. https://github.com/planetarium/NineChronicles/blob/2b6e962e6f3feeaf1a7cf5e83cbef78f0474a5bf/nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs#L63

File: nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs [hunk 5]
```diff
@@ -118,10 +119,8 @@ private static void UpdateGoldBalanceState(GoldBalanceState goldBalanceState)
             States.Instance.SetGoldBalanceState(goldBalanceState);
         }
 
-        private async void UpdateAvatarState(AvatarState avatarState, int index)
-        {
+        private async Task UpdateAvatarState(AvatarState avatarState, int index) =>
```
Comment (longfin) [inline nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs:122]:
```suggestion
        private Task UpdateAvatarState(AvatarState avatarState, int index) =>
```

File: nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs [hunk 6]
```diff
@@ -118,10 +119,8 @@ private static void UpdateGoldBalanceState(GoldBalanceState goldBalanceState)
...
             await States.Instance.AddOrReplaceAvatarState(avatarState, index);
```
Comment (longfin) [inline nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs:123]:
```suggestion
            States.Instance.AddOrReplaceAvatarState(avatarState, index);
```

**Review by area363 — APPROVED** [review]

**Review by longfin — APPROVED** [review]
