### PR TITLE
Prevent crash when stream hang

### LINKED ISSUE #987: Game crashes when shutdown
# Environment
- v100087
- in RPC mode

# Steps to reproduce
- Launch the game through the game launcher
- Execute battle(`HackAndSlash`) once (or more?)
- Close 9c.exe

# Excpected behavior
- 9c.exe should be turned off without any error

# Actual behavior
image

[Player.log](https://github.com/planetarium/NineChronicles/files/7592666/Player.log)

### PR DESCRIPTION
**Pull request by ipdae**
### Description

- resolve #987 

### How to test

1. run local headless with rpc configuration
2. set `Thread.Sleep` in headless [GetState](https://github.com/planetarium/NineChronicles.Headless/blob/v100089/NineChronicles.Headless/BlockChainService.cs#L87-L94) before return  
3. build 9c client

### CODE REVIEW

File: nekoyume/Assets/_Scripts/BlockChain/ClientFilter.cs [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+namespace Nekoyume.BlockChain
+{
+    public class ClientFilter : IClientFilter
+    {
+        public async ValueTask<ResponseContext> SendAsync(RequestContext context, Func<RequestContext, ValueTask<ResponseContext>> next)
+        {
+            try
+            {
+                var response = await next(context); /* Call next filter or method body */
+                return response;
```
Comment (longfin) [inline nekoyume/Assets/_Scripts/BlockChain/ClientFilter.cs:15]: Should we `await` return value(`response`) instead of returning directly?

**Review by longfin — APPROVED** [review]
